import type { BunkerRow, PhysicalOpportunityRow, RouteDistanceRow, VesselSpecRow } from "../types";

export const vesselFixture: VesselSpecRow = {
  vessel_name: "Fixture Panamax",
  segment: "PANAMAX",
  dwt: 82450,
  cbm: 98600,
  built_year: 2018,
  age: 8,
  scrubber_fitted: false,
  loa: 229,
  beam: 32.3,
  draft: 14.4,
  laden_speed: 13.7,
  laden_consumption: 30,
  ballast_speed: 14.2,
  ballast_consumption: 28,
  eco_laden_speed: 12,
  eco_laden_consumption: 21,
  eco_ballast_speed: 12.6,
  eco_ballast_consumption: 22,
  port_working_consumption: 4,
  port_idle_consumption: 2.8,
  fuel_type_main: "VLSFO",
  fuel_type_scrubber: "HSFO",
  mgo_consumption: 0.1,
  commercial_premium_or_discount: 450,
};

export const opportunityFixture: PhysicalOpportunityRow = {
  opportunity_id: "FIXTURE-PAN-P6",
  vessel_name: vesselFixture.vessel_name,
  trade_type: "TC_IN_AND_VOYAGE",
  route_code: "FIXTURE_P6_ROUTE",
  delivery_area: "Singapore",
  redelivery_area: "Singapore",
  load_port: "Geraldton",
  discharge_port: "Qingdao",
  laycan_start: "2026-05-22",
  laycan_end: "2026-05-27",
  cargo_qty: 76000,
  freight_rate: 24.5,
  tc_in_hire: 13250,
  tc_out_hire: 0,
  voyage_days: 43,
  ballast_days: 11,
  laden_days: 18,
  port_days: 8,
  waiting_days: 4,
  canal_days: 2,
  commission_pct: 2.5,
  port_costs: 185000,
  canal_costs: 0,
  misc_costs: 45000,
  employment_status: "FIXED",
  route_exposure: { P6_82: 1 },
};

export const bunkerFixture: BunkerRow = {
  date: "2026-05-21",
  port: "Singapore",
  VLSFO: 586,
  HSFO: 436,
  MGO: 716,
  MFO: 510,
  currency: "USD",
};

export const routeFixture: RouteDistanceRow = {
  route_code: opportunityFixture.route_code,
  benchmark_family: "PANAMAX",
  load_port: "Geraldton",
  discharge_port: "Qingdao",
  ballast_start: "Singapore",
  laden_distance: 3450,
  ballast_distance: 2600,
  canal_required: false,
  standard_waiting_days: 3,
  standard_load_days: 4,
  standard_discharge_days: 4,
  weather_margin: 0.06,
  standard_commission: 5,
  standard_cargo_qty: 76000,
  exposure: { P6_82: 1 },
  route_notes: "Test fixture route for physical economics tests.",
};

