import type { RouteDistanceRow } from "../types";

export const routeDefinitions: RouteDistanceRow[] = [
  {
    route_code: "P1A_82_ATLANTIC_RV",
    benchmark_family: "PANAMAX",
    load_port: "Atlantic",
    discharge_port: "Atlantic",
    ballast_start: "Skaw-Gibraltar range",
    laden_distance: 5200,
    ballast_distance: 3000,
    canal_required: false,
    standard_waiting_days: 3,
    standard_load_days: 4,
    standard_discharge_days: 4,
    weather_margin: 0.06,
    standard_commission: 5,
    standard_cargo_qty: 75000,
    exposure: { P1A_82: 1 },
    route_notes: "GMG Panamax Atlantic round voyage component. Distances are user-editable assumptions and not official Baltic distances.",
  },
  {
    route_code: "P2A_82_FRONTHAUL",
    benchmark_family: "PANAMAX",
    load_port: "Atlantic",
    discharge_port: "Asia",
    ballast_start: "Skaw-Gibraltar range",
    laden_distance: 11000,
    ballast_distance: 2400,
    canal_required: true,
    standard_waiting_days: 3,
    standard_load_days: 4,
    standard_discharge_days: 4,
    weather_margin: 0.06,
    standard_commission: 5,
    standard_cargo_qty: 75000,
    exposure: { P2A_82: 1 },
    route_notes: "GMG Panamax Atlantic to Asia fronthaul component. Distances are assumption placeholders.",
  },
  {
    route_code: "P3A_82_PACIFIC_RV",
    benchmark_family: "PANAMAX",
    load_port: "Pacific",
    discharge_port: "Pacific",
    ballast_start: "Japan-South Korea range",
    laden_distance: 5600,
    ballast_distance: 2200,
    canal_required: false,
    standard_waiting_days: 3,
    standard_load_days: 4,
    standard_discharge_days: 4,
    weather_margin: 0.06,
    standard_commission: 5,
    standard_cargo_qty: 75000,
    exposure: { P3A_82: 1 },
    route_notes: "GMG Panamax Pacific round voyage component. Distances are assumption placeholders.",
  },
  {
    route_code: "P4_82_BACKHAUL",
    benchmark_family: "PANAMAX",
    load_port: "Pacific",
    discharge_port: "Atlantic",
    ballast_start: "Japan-South Korea range",
    laden_distance: 9800,
    ballast_distance: 1800,
    canal_required: true,
    standard_waiting_days: 3,
    standard_load_days: 4,
    standard_discharge_days: 4,
    weather_margin: 0.06,
    standard_commission: 5,
    standard_cargo_qty: 75000,
    exposure: { P4_82: 1 },
    route_notes: "GMG Panamax Pacific to Atlantic backhaul component. P4_82 remains valid although P4TC-FFA is removed.",
  },
  {
    route_code: "BLPG1_MEG_JAPAN",
    benchmark_family: "BLPG",
    load_port: "Ras Tanura",
    discharge_port: "Chiba",
    ballast_start: "Middle East Gulf",
    laden_distance: 6500,
    ballast_distance: 6500,
    canal_required: false,
    standard_waiting_days: 0.5,
    standard_load_days: 2,
    standard_discharge_days: 2,
    weather_margin: 0.07,
    standard_commission: 1.25,
    standard_cargo_qty: 44000,
    exposure: { BLPG1: 1 },
    route_notes: "GMG BLPG1 44,000mt LPG Ras Tanura to Chiba; TCE route uses 2 load days, 2 discharge days, 0.5 waiting day.",
  },
  {
    route_code: "BLPG2_USG_CONT",
    benchmark_family: "BLPG",
    load_port: "Houston",
    discharge_port: "Flushing",
    ballast_start: "US Gulf",
    laden_distance: 5200,
    ballast_distance: 5200,
    canal_required: false,
    standard_waiting_days: 0.5,
    standard_load_days: 2,
    standard_discharge_days: 2,
    weather_margin: 0.07,
    standard_commission: 1.25,
    standard_cargo_qty: 44000,
    exposure: { BLPG2: 1 },
    route_notes: "GMG BLPG2 44,000mt LPG Houston to Flushing; TCE route uses 2 load days, 2 discharge days, 0.5 waiting day.",
  },
  {
    route_code: "BLPG3_USG_JAPAN",
    benchmark_family: "BLPG",
    load_port: "Houston",
    discharge_port: "Chiba",
    ballast_start: "US Gulf",
    laden_distance: 9500,
    ballast_distance: 5200,
    canal_required: true,
    standard_waiting_days: 0.5,
    standard_load_days: 2,
    standard_discharge_days: 2,
    weather_margin: 0.07,
    standard_commission: 1.25,
    standard_cargo_qty: 44000,
    exposure: { BLPG3: 1 },
    route_notes: "GMG BLPG3 44,000mt LPG Houston to Chiba via Panama Canal; $/mt route includes Panama waiting assumptions.",
  },
];

